url: "https://redstonemango.github.io"
theme: jekyll-theme-cayman
description: "" # Explicitly nothing to avoid " | DESCRIPTION" in website title

collections:
  blogs:
    output: true
    permalink: /blogs/:name/